name: Compile LaTeX and Convert to PNG

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile-and-convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full imagemagick

    - name: Compile .tex files to .pdf
      run: |
        for file in *.tex; do
          pdflatex -interaction=nonstopmode "$file";
        done

    - name: Convert .pdf to .png
      run: |
        for file in *.pdf; do
          convert -density 300 "$file" "${file%.pdf}.png";
        done

    - name: Save output PDFs and PNGs
      run: |
        for file in *.tex; do
          mv "${file%.tex}.pdf" "${file%.tex}.png" ./
        done

    - name: Commit and push results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add *.pdf *.png
        git commit -m "Add compiled PDFs and PNGs"
        git push
