name: LaTeX Compilation

on:
  push:
    branches:
      - master
    paths:
      - "**/*.tex"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX files
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "**/*.tex"
          args: -pdf -interaction=nonstopmode -shell-escape

      - name: Convert to PNG
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils
          find . -name "*.pdf" -not -name "typst-*" -print0 | while IFS= read -r -d '' pdf; do
            echo "Converting $pdf to PNG..."
            pdftocairo -png -singlefile -transp -r 300 "$pdf" "${pdf%.pdf}"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format and compile LaTeX files"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
          file_pattern: "*.pdf *.png"
