name: Typst Compilation

on:
  push:
    branches:
      - master
    paths:
      - "**/*.typ"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Compile and Convert
        run: |
          sudo apt-get update && sudo apt-get install -y poppler-utils
          find . -name "*.typ" -print0 | while IFS= read -r -d '' file; do
            pdf="${file%.typ}.pdf"
            png="${file%.typ}.png"
            
            echo "Compiling $file..."
            typst compile "$file" "$pdf"
            
            echo "Converting $pdf to $png..."
            pdftocairo -png -singlefile -transp -r 300 "$pdf" "${pdf%.pdf}"
          done

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format and compile Typst files"
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          commit_author: Author <actions@github.com>
          file_pattern: "*.pdf *.png"
